### ISSUE TITLE
Environment state

### ISSUE THREAD

**Issue by ghost** [EderSantana/X#5]
I'm working on the game snake, which extends the Environment class, but cannot make it 100% compatible...

See: https://github.com/bitwise-ben/X/blob/feature/snake/x/environment.py

That's because a simplified representation in terms of position of fruit / basket is not the same as the representation of a snake, which contains a location for each segment. Thus, observe and state return matrices (i.e., a frame/screen) in my implementation.

Probably, in the future when there are games that have more than two in-game objects it's easier to return a frame/screen as state, isn't it?

My question is, what should I do with my current implementation?

**Comment by EderSantana** [comment]
Tkx for looking into this @bitwise-ben 
So, the exposed and internal states can be different. For example the exposed state could be the entire picture of the game and the internal state is everything you need to keep the game running. The fruit game (optionally) returns pixel locations just to make the table based model work. But we don't expect that all the environments have such a simple representation. You can make the snake game image based only. No problem.

Let us know how we can help in your implementation.

**Comment by ghost** [comment]
Thanks for explaining what state and observe should return. I think that my feature branch meets the requirements, and I've submitted a pull request.

**Comment by EderSantana** [comment]
Cool! Merged! We will work on this further! Let me know if you want to do any other PR
